const errors = {
    INVALID_TYPE: "invalidType",
    CUSTOM_ERROR: "customError",
    INVALID_UNION: "invalidUnion",
    INVALID_ENUM_VALUE: "invalidEnumValue",
    UNRECOGNIZED_KEYS: "unrecognizedKeys",
    INVALID_ARGUMENTS: "invalidArguments",
    INVALID_RETURN_TYPE: "invalidReturnType",
    INVALID_DATE: "invalidDate",
    INVALID_STRING: "invalidString",
    TOO_SMALL_STRING: "tooSmallString",
    TOO_SMALL_NUMBER: "tooSmallNumber",
    TOO_SMALL_ARRAY: "tooSmallArray",
    TOO_BIG_STRING: "tooBigString",
    TOO_BIG_NUMBER: "tooBigNumber",
    TOO_BIG_ARRAY: "tooBigArray",
    INVALID_INTERSECTION_TYPES: "invalidIntersectionTypes",
    NOT_MULTIPLE_OF: "notMultipleOf",
    NOT_FINITE: "notFinite",
};
